#!/bin/bash

local_storage_location="/etc/local.konteiner.sh"
terraform_plugin_location="${local_storage_location}/terraform-plugins"
host_variables="${local_storage_location}/host-variables.tfvars"
secrets="${local_storage_location}/secrets.tfvars"
branch_name=`git rev-parse --abbrev-ref HEAD`
state_file="${local_storage_location}/$branch_name.tfstate"
orchestration="cattle"
driver="digitalocean"

terraform init -plugin-dir $terraform_plugin_location rancher
terraform get rancher
terraform destroy -var "rancher_environment_name=$branch_name" -var "driver=$driver" -var "orchestration=$orchestration" -var-file=$secrets -var-file=$host_variables -state=$state_file -state-out=$state_file rancher
