version: '2'
services:
  nfs-driver:
    privileged: true
    image: rancher/storage-nfs:v0.6.5
    environment:
      MOUNT_DIR: /volume/rancher
      MOUNT_OPTS: ',nfsvers=4'
      NFS_SERVER: 10.135.47.139
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    pid: host
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
